## 自定义异常
> 用户自定义异常类，只需要继承 `Exception` 类即可。

### 在程序中使用自定义异常类，大体可以分为以下几个步骤：
1. 创建自定义异常类；
2. 在方法中通过 `throw` 关键字抛出异常对象；
3. 如果在当前排除异常的方法中处理异常，可以使用 `try-catch` 语句捕获并处理，否则在方法的生命出通过 `throws` 关键字指明要抛出给方法调用着的异常，继续进行下一步操作；
4. 在出现异常方法的店面用者中捕获并处理异常。

### 自定义异常
1. 直接使用 `Exception` 的报错提示；
```java
// 继承 Exception 即可
public class MyException extends Exception {
    public MyException(String message) {
        // 使用 Exception 的报错提示 ，此时错误描述信息通过 new 时传递。
        super(message);
    }
}

public class Test {
    public static void main(String[] args) {
        try {
            doSomething(11);
        } catch (MyException e) {
            //  e.printStackTrace();
            System.out.println(e); // MyException
        }
    }

    // throws 抛出给方法的调用者捕获
    public static void doSomething(int num) throws MyException {
        // 如果 num > 10 就抛出自定义异常
        if (num > 10) {
            // 手动传递错误信息
            throw new MyException("num > 10");
        } else {
            System.out.println("没有异常，num为" + num);
        }
    }
}
```

2. 自定义错误信息
```java
public class MyException extends Exception {
    private int num;
    public MyException(int num) {
        this.num = num;
    }
    
    // 自定义错误信息
    @Override
    public String toString() {
            return "MyException{" + this.num + "大于10}";
    }
}
```
